title: First Site using GitHub Pages
author: Surya
email: rathoresurya21@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Web Developer and Completing my GitHub course here and enjoying learning github
# adding a theme
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
